CREATE DATABASE company;
USE company;

CREATE TABLE regions(
    REGION_ID INTEGER PRIMARY KEY,
    REGION_NAME VARCHAR(25)
);

CREATE TABLE countries(
    COUNTRY_ID VARCHAR(2) PRIMARY KEY,
    COUNTRY_NAME VARCHAR(40),
    REGION_ID INTEGER,
    FOREIGN KEY (REGION_ID) REFERENCES regions(REGION_ID) 
);

CREATE TABLE locations(
    LOCATION_ID INTEGER PRIMARY KEY,
    STREET_ADDRESS VARCHAR(25),
    POSTAL_CODE VARCHAR(12),
    CITY VARCHAR(30),
    STATE_PROVINCE VARCHAR(12),
    COUNTRY_ID VARCHAR(2),
    FOREIGN KEY (COUNTRY_ID) REFERENCES countries(COUNTRY_ID) ON DELETE CASCADE
);

CREATE TABLE departments(
    DEPARTMENT_ID INTEGER PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(30),
    MANAGER_ID INTEGER,
    LOCATION_ID INTEGER,
    FOREIGN KEY (LOCATION_ID) REFERENCES locations(LOCATION_ID)
);

CREATE TABLE jobs(
    JOB_ID VARCHAR(10) PRIMARY KEY,
    JOB_TITLE VARCHAR(35),
    MIN_SALARY INTEGER,
    MAX_SALARY INTEGER
);

CREATE TABLE job_history(
    EMPLOYEE_ID INTEGER,
    START_DATE DATE,
    END_DATE DATE,
    JOB_ID VARCHAR(10),
    DEPARTMENT_ID INTEGER,
    PRIMARY KEY (EMPLOYEE_ID, START_DATE),
    FOREIGN KEY (JOB_ID) REFERENCES jobs(JOB_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES departments(DEPARTMENT_ID)
);

CREATE TABLE employees(
    EMPLOYEE_ID INTEGER PRIMARY KEY,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(25),
    EMAIL VARCHAR(200),
    PHONE_NUMBER VARCHAR(10),
    HIRE_DATE DATE,
    JOB_ID VARCHAR(10),
    SALARY INTEGER,
    COMMISSION_PCT INTEGER,
    MANAGER_ID INTEGER,
    DEPARTMENT_ID INTEGER,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES job_history(EMPLOYEE_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES departments(DEPARTMENT_ID)
);

CREATE TABLE job_grades(
    GRADE_LEVEL VARCHAR(2) PRIMARY KEY,
    LOWEST_SAL INTEGER,
    HIGHEST_SAL INTEGER
);

